#!perl                                 -*- cperl -*-

sub initialize_input {
  my ($ctx, @inputs) = @_;
 INPUT:
  for my $input (@inputs) {
    next unless $input->type eq "file";
    my $path = $input->{path} or die "Input item missing path!\n";
    open my($fh), "<", $path or do {
      $ctx->warn("Couldn't open path '$path' for reading: $!; skipping\n");
      next INPUT;
    };
    { local $/;
      $input->{raw_data} = <$fh>;
    }
  }
}

1;

